name: Build NixOS ISO

on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
      with:
        ref: flakes

    - name: Set up Nix
      uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Build ISO image
      run: nix build --impure .#nixosConfigurations.isoimage.config.system.build.isoImage

    - name: Upload ISO artifact
      uses: actions/upload-artifact@v3
      with:
        name: coffeeispower-nixos-iso
        path: ./result/iso/*.iso
